services:
  # wallet.api:
  #   image: ${DOCKER_REGISTRY-}walletapi
  #   build:
  #     context: .
  #     dockerfile: Demo/Wallet.API/Dockerfile
  event_store_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - 5432:5432



